<a href="https://colab.research.google.com/github/Carlos1729/todojson/blob/main/Pytorch_Fundamentals_Madhukar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
#Random Tensors
import torch

In [37]:
random_tensor = torch.rand(3,4)
print(random_tensor)#ndims will be what goes inside .rand

tensor([[0.7735, 0.6045, 0.3651, 0.9747],
        [0.0781, 0.9819, 0.6282, 0.1487],
        [0.1703, 0.5465, 0.8723, 0.9178]])


In [38]:
random_tensor.ndim

2

In [39]:
random_image_tensor = torch.rand(224,224,3) #similar to an rcb image tensor

In [40]:
random_image_tensor, random_image_tensor.shape, random_image_tensor.ndim

(tensor([[[0.8082, 0.2640, 0.5527],
          [0.6231, 0.3800, 0.7341],
          [0.3352, 0.8859, 0.4339],
          ...,
          [0.6279, 0.8249, 0.3502],
          [0.1993, 0.9566, 0.3327],
          [0.1372, 0.8896, 0.6469]],
 
         [[0.2261, 0.4744, 0.9987],
          [0.5812, 0.1544, 0.0968],
          [0.3887, 0.2780, 0.5149],
          ...,
          [0.3872, 0.2141, 0.6957],
          [0.9547, 0.0035, 0.1570],
          [0.0670, 0.0958, 0.3637]],
 
         [[0.4926, 0.5262, 0.4822],
          [0.9419, 0.3682, 0.4211],
          [0.8080, 0.7073, 0.7791],
          ...,
          [0.8522, 0.4973, 0.2764],
          [0.8858, 0.7069, 0.2966],
          [0.6417, 0.2598, 0.1451]],
 
         ...,
 
         [[0.5360, 0.8319, 0.0713],
          [0.9517, 0.1198, 0.7489],
          [0.6897, 0.4527, 0.1326],
          ...,
          [0.5316, 0.6183, 0.0523],
          [0.0278, 0.4762, 0.1301],
          [0.0665, 0.4159, 0.1030]],
 
         [[0.9397, 0.2357, 0.5239],
          [0

In [41]:
#zeroes and ones tensors

In [42]:
zeros = torch.zeros(3,4)

In [43]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [44]:
ones = torch.ones(4,3)

In [45]:
ones , ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [46]:
torch.range(0,10)

<ipython-input-46-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [47]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
r = torch.arange(1,10,2)
r

tensor([1, 3, 5, 7, 9])

In [49]:
#create a tensor with similar shape of another given tensor
zeros = torch.zeros_like(r)
zeros
ones = torch.ones_like(r)
ones  #the _like doest work with torch.rand why

tensor([1, 1, 1, 1, 1])

In [50]:
tenso = torch.rand(3,4,dtype=torch.float16)
tenso

tensor([[0.6323, 0.4971, 0.5840, 0.6636],
        [0.3755, 0.0952, 0.6982, 0.5547],
        [0.9321, 0.1445, 0.0664, 0.3184]], dtype=torch.float16)

In [51]:
# dtype - type of elements inside the tensor
# device - if gpu enabled cuda, or else cpu
# requires - grad wether or not to track gradients with these operations

In [52]:
ones.shape, tenso.shape

(torch.Size([5]), torch.Size([3, 4]))

In [53]:
# ones * tenso * is for element wise multiplication for matrix multiplication use @
ones @ tenso

RuntimeError: ignored

In [54]:
tenso = torch.rand(3,4,dtype=torch.float32)
tenso

tensor([[0.6252, 0.2554, 0.8271, 0.0328],
        [0.8364, 0.8524, 0.8165, 0.5252],
        [0.1726, 0.8055, 0.2303, 0.7713]])

In [55]:
ones @ tenso

RuntimeError: ignored

In [56]:
print(tenso.dtype)
print(tenso.shape)
print(tenso.device)

torch.float32
torch.Size([3, 4])
cpu


In [57]:
##Manipulating tensors

In [58]:
zeros = torch.zeros(3,4)

In [59]:
ones + tenso

RuntimeError: ignored

In [60]:
zeros.shape , tenso.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [61]:
zeros + tenso

tensor([[0.6252, 0.2554, 0.8271, 0.0328],
        [0.8364, 0.8524, 0.8165, 0.5252],
        [0.1726, 0.8055, 0.2303, 0.7713]])

In [62]:
zeros - tenso

tensor([[-0.6252, -0.2554, -0.8271, -0.0328],
        [-0.8364, -0.8524, -0.8165, -0.5252],
        [-0.1726, -0.8055, -0.2303, -0.7713]])

In [63]:
ones - tenso

RuntimeError: ignored

In [64]:
zeros * tenso

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [65]:
ones * tenso

RuntimeError: ignored

In [66]:
ones @ tenso

RuntimeError: ignored

In [67]:
zeros @ tenso

RuntimeError: ignored

In [68]:
torch.matmul(ones,tenso)

RuntimeError: ignored

In [69]:
torch.matmul(zeros,tenso)

RuntimeError: ignored

In [70]:
torch.mm(ones,tenso)

RuntimeError: ignored

In [71]:
zeros @ tenso.T #take the teranspose

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [72]:
tenso.min()

tensor(0.0328)

In [73]:
tenso.max()

tensor(0.8524)

In [74]:
tenso.mean() #this worked because the dtypre is not int

tensor(0.5626)

In [75]:
tenso.sum()

tensor(6.7506)

In [76]:
tenso.argmin()#1d based indexing

tensor(3)

In [77]:
tenso.argmax()

tensor(5)

In [80]:
#Reshaping - changee shape of given tensor
# view - return a view of tensor of certain shape but with the memory as original tensor
#stacking - vertical stack of tensors
#horizontal stacking - horizontal stack of different tensors
#squeeze =- remove all 1 dimensions  from a tensor
#unsqueeze - adds 1 dimension to the tensor
#permute - reorders the tensor basically the dimensions will be getting swapped in a particular order

In [82]:
x = torch.arange(1,10)
x , x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [83]:
x_reshaped = x.reshape(1,7) #total no of elements after reshape should be sdame as the total no of elements beforwe reshape
x_reshaped, x_reshaped.shape

RuntimeError: ignored

In [84]:
x_reshaped = x.reshape(1,9) #total no of elements after reshape should be sdame as the total no of elements beforwe reshape
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [85]:
x_reshaped = x.reshape(9,1) #total no of elements after reshape should be sdame as the total no of elements beforwe reshape
x_reshaped, x_reshaped.shape

(tensor([[1],
         [2],
         [3],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]),
 torch.Size([9, 1]))

In [86]:
#change the view

In [88]:
z = x.view(1,9)#view basically gives you a part of the origiinal tensor basically it is showing the orinial tensor but only a part of it
z , z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [89]:
z = x.view(1,5)#view basically gives you a part of the origiinal tensor basically it is showing the orinial tensor but only a part of it
z , z.shape

RuntimeError: ignored

In [92]:
z[:, 2] = 4
z, x

(tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9]]), tensor([1, 2, 4, 4, 5, 6, 7, 8, 9]))

In [95]:
x_stack = torch.stack([x,x,x,x,x])
x_stack

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [96]:
x_stack = torch.stack([x,x,x,x,x],0)
x_stack

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9],
        [1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [97]:
x_stack = torch.stack([x,x,x,x,x],1)
x_stack

tensor([[1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2],
        [4, 4, 4, 4, 4],
        [4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9]])

In [99]:
x_stack = torch.stack([x,x,x,x,x],2)#torch.vstack,torch.hstack()
x_stack

IndexError: ignored

In [100]:
# The main difference between view() and reshape() lies in how they handle contiguous memory layouts. view() requires the tensor's memory layout to be contiguous (elements are stored in adjacent
# memory locations), whereas reshape() can work with non-contiguous memory layouts by creating a new tensor with the specified shape. If you want to ensure that the reshaping is only allowed for
# contiguous tensors, you can use the contiguous() method in combination with view().

In [101]:
# Certainly! Let's explore an example that demonstrates the difference between `view()` and `reshape()` when it comes to working with contiguous and non-contiguous tensors.

# ```python
# import torch

# # Creating a non-contiguous tensor
# tensor = torch.tensor([[1, 2, 3], [4, 5, 6]])
# non_contig_tensor = tensor[:, 1:]

# # Using view() on a non-contiguous tensor
# try:
#     view_result = non_contig_tensor.view(3)
# except RuntimeError as e:
#     view_result = str(e)

# # Using reshape() on a non-contiguous tensor
# reshape_result = non_contig_tensor.reshape(3)

# print("Original tensor:")
# print(tensor)

# print("\nNon-contiguous tensor:")
# print(non_contig_tensor)

# print("\nview() result on non-contiguous tensor:")
# print(view_result)

# print("\nreshape() result on non-contiguous tensor:")
# print(reshape_result)
# ```

# In this example, we start with a non-contiguous tensor by selecting a subset of columns from the original tensor. The non-contiguous tensor is created using slicing (`tensor[:, 1:]`).

# When we attempt to use `view()` on the non-contiguous tensor, it raises a `RuntimeError` because `view()` requires contiguous memory layout. However, when we use `reshape()`, it's able to create a new tensor with the desired shape even for a non-contiguous tensor.

# The `reshape()` method, in this case, creates a new tensor with the desired shape, which may involve copying the data to ensure contiguity. On the other hand, `view()` tries to work with the existing memory layout and only changes the shape without copying data.

# Keep in mind that while `reshape()` can work with non-contiguous tensors, it's generally recommended to use `contiguous()` when you want to reshape a tensor with `view()`, especially if you encounter issues related to memory layout.

In [103]:
# Certainly! Here's the complete output of the code I provided earlier:

# ```
# Original tensor:
# tensor([[1, 2, 3],
#         [4, 5, 6]])

# Non-contiguous tensor:
# tensor([[2, 3],
#         [5, 6]])

# view() result on non-contiguous tensor:
# view is not supported on Tensor that doesn't have a contiguous memory layout. Use .contiguous() to make a contiguous copy of the tensor or use .reshape(...) which returns a contiguous tensor.

# reshape() result on non-contiguous tensor:
# tensor([2, 3, 5])
# ```

# In the output, you can see how `view()` raises an error due to the non-contiguous memory layout of the tensor, while `reshape()` successfully reshapes the tensor even though it's non-contiguous. Keep in mind that using `contiguous()` before `view()` is a common practice when you need to reshape tensors with non-contiguous memory layouts.

In [104]:
# The non-contiguous memory layout of the second tensor in the example is a consequence of how tensor operations are performed and how data is stored in memory.

# In the code example I provided earlier, the second tensor is created using slicing from the original tensor:

# ```python
# non_contig_tensor = tensor[:, 1:]
# ```

# Here's why the resulting tensor has a non-contiguous memory layout:

# 1. **Memory Storage Order:** In PyTorch, tensors are stored in memory using a contiguous block of memory. The default storage order is row-major, meaning that elements along the same row are stored in contiguous memory locations.

# 2. **Slicing Operation:** When you perform a slicing operation like `tensor[:, 1:]`, you are creating a new tensor that references a subset of the original tensor's data. However, this subset doesn't necessarily maintain the contiguous memory layout, especially when you're slicing along a dimension (columns in this case).

# 3. **Strided Views:** The non-contiguous tensor created through slicing becomes what is called a "strided view." A strided view means that elements are not stored in contiguous memory locations, but the tensor maintains information about strides (step sizes) to access the elements.

# While PyTorch allows creating strided views for various operations, certain operations like `view()` and many optimized operations require the tensor to have a contiguous memory layout to work efficiently.

# In practice, the non-contiguous memory layout can lead to performance inefficiencies and compatibility issues with certain operations. That's why it's often recommended to use `.contiguous()` to create a contiguous copy of the tensor before performing operations that require contiguous memory layout.

In [105]:
#torch.sqeez

In [112]:
x_reshaped

tensor([[1],
        [2],
        [4],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [113]:
x_reshaped.shape

torch.Size([9, 1])

In [117]:
x_squeexed = x_reshaped.squeeze()

In [115]:
x_reshaped.squeeze().shape

torch.Size([9])

In [118]:
x_squeexed.unsqueeze(0)

tensor([[1, 2, 4, 4, 5, 6, 7, 8, 9]])

In [120]:
x_reshaped.unsqueeze(0)

tensor([[[1],
         [2],
         [4],
         [4],
         [5],
         [6],
         [7],
         [8],
         [9]]])

In [121]:
x_reshaped.unsqueeze(1)

tensor([[[1]],

        [[2]],

        [[4]],

        [[4]],

        [[5]],

        [[6]],

        [[7]],

        [[8]],

        [[9]]])

In [128]:
imzge =  torch.rand((224,224,3))
imzge

tensor([[[0.3884, 0.0418, 0.5394],
         [0.9159, 0.4581, 0.3791],
         [0.9551, 0.6443, 0.4720],
         ...,
         [0.3431, 0.0845, 0.1484],
         [0.5479, 0.5657, 0.4579],
         [0.3884, 0.6907, 0.4542]],

        [[0.8176, 0.0522, 0.5894],
         [0.3237, 0.6892, 0.7368],
         [0.6711, 0.3127, 0.9294],
         ...,
         [0.1334, 0.7484, 0.2566],
         [0.3911, 0.2639, 0.2684],
         [0.4519, 0.5257, 0.5468]],

        [[0.0812, 0.6124, 0.6706],
         [0.4262, 0.6362, 0.9508],
         [0.7628, 0.1543, 0.0205],
         ...,
         [0.2556, 0.0552, 0.1988],
         [0.9642, 0.7406, 0.7791],
         [0.4678, 0.9303, 0.6035]],

        ...,

        [[0.8857, 0.7216, 0.0769],
         [0.7380, 0.1855, 0.0499],
         [0.5797, 0.7311, 0.9447],
         ...,
         [0.6239, 0.5164, 0.5231],
         [0.8504, 0.5751, 0.3761],
         [0.0062, 0.3619, 0.1619]],

        [[0.2237, 0.5684, 0.6653],
         [0.6194, 0.0333, 0.3379],
         [0.

In [130]:
imzp = imzge.permute(2,0,1)
imzp

tensor([[[0.3884, 0.9159, 0.9551,  ..., 0.3431, 0.5479, 0.3884],
         [0.8176, 0.3237, 0.6711,  ..., 0.1334, 0.3911, 0.4519],
         [0.0812, 0.4262, 0.7628,  ..., 0.2556, 0.9642, 0.4678],
         ...,
         [0.8857, 0.7380, 0.5797,  ..., 0.6239, 0.8504, 0.0062],
         [0.2237, 0.6194, 0.6853,  ..., 0.8962, 0.0903, 0.5477],
         [0.0376, 0.7803, 0.3293,  ..., 0.4640, 0.6215, 0.3352]],

        [[0.0418, 0.4581, 0.6443,  ..., 0.0845, 0.5657, 0.6907],
         [0.0522, 0.6892, 0.3127,  ..., 0.7484, 0.2639, 0.5257],
         [0.6124, 0.6362, 0.1543,  ..., 0.0552, 0.7406, 0.9303],
         ...,
         [0.7216, 0.1855, 0.7311,  ..., 0.5164, 0.5751, 0.3619],
         [0.5684, 0.0333, 0.8058,  ..., 0.8019, 0.3345, 0.6443],
         [0.0715, 0.1888, 0.3355,  ..., 0.6862, 0.8580, 0.8087]],

        [[0.5394, 0.3791, 0.4720,  ..., 0.1484, 0.4579, 0.4542],
         [0.5894, 0.7368, 0.9294,  ..., 0.2566, 0.2684, 0.5468],
         [0.6706, 0.9508, 0.0205,  ..., 0.1988, 0.7791, 0.

In [131]:
imzge.permute(2,0,1).shape

torch.Size([3, 224, 224])

In [133]:
print(imzge[0])
print(imzp[0])

tensor([[0.3884, 0.0418, 0.5394],
        [0.9159, 0.4581, 0.3791],
        [0.9551, 0.6443, 0.4720],
        [0.9516, 0.7438, 0.9195],
        [0.3749, 0.8810, 0.2361],
        [0.4818, 0.4137, 0.2697],
        [0.6779, 0.3514, 0.8485],
        [0.1930, 0.9609, 0.6142],
        [0.5251, 0.8928, 0.9013],
        [0.7186, 0.2689, 0.6336],
        [0.6199, 0.6306, 0.8140],
        [0.7034, 0.0730, 0.9567],
        [0.9192, 0.5180, 0.1347],
        [0.7352, 0.7298, 0.2912],
        [0.8824, 0.5117, 0.7161],
        [0.1811, 0.9415, 0.9187],
        [0.2112, 0.4104, 0.0401],
        [0.6532, 0.2058, 0.7748],
        [0.9650, 0.0286, 0.6795],
        [0.7045, 0.4179, 0.2951],
        [0.2054, 0.1332, 0.9615],
        [0.8692, 0.6216, 0.2842],
        [0.3087, 0.0761, 0.3464],
        [0.0877, 0.7623, 0.2139],
        [0.7187, 0.5146, 0.5484],
        [0.3725, 0.4746, 0.5845],
        [0.3235, 0.4560, 0.5978],
        [0.3181, 0.6273, 0.2422],
        [0.8815, 0.2044, 0.6552],
        [0.562

In [134]:
print(imzge[0][0])
print(imzp[0][0])

tensor([0.3884, 0.0418, 0.5394])
tensor([0.3884, 0.9159, 0.9551, 0.9516, 0.3749, 0.4818, 0.6779, 0.1930, 0.5251,
        0.7186, 0.6199, 0.7034, 0.9192, 0.7352, 0.8824, 0.1811, 0.2112, 0.6532,
        0.9650, 0.7045, 0.2054, 0.8692, 0.3087, 0.0877, 0.7187, 0.3725, 0.3235,
        0.3181, 0.8815, 0.5621, 0.4974, 0.1605, 0.2795, 0.2288, 0.4093, 0.9155,
        0.1321, 0.8447, 0.7633, 0.3307, 0.4978, 0.5159, 0.5682, 0.0152, 0.8562,
        0.1751, 0.8463, 0.3306, 0.2909, 0.2652, 0.9398, 0.0516, 0.4624, 0.9883,
        0.0539, 0.5795, 0.1396, 0.5084, 0.9927, 0.7119, 0.1780, 0.0952, 0.4372,
        0.1916, 0.4342, 0.3194, 0.3142, 0.9503, 0.1900, 0.1071, 0.6639, 0.7657,
        0.0625, 0.3500, 0.1783, 0.0484, 0.6079, 0.8358, 0.6557, 0.3373, 0.0914,
        0.1677, 0.2678, 0.9724, 0.5005, 0.0406, 0.6202, 0.6336, 0.5804, 0.2128,
        0.6514, 0.3834, 0.5445, 0.1863, 0.9256, 0.8624, 0.7588, 0.2240, 0.7931,
        0.7647, 0.8000, 0.4011, 0.8014, 0.5853, 0.4928, 0.0248, 0.9265, 0.9495,
       

In [135]:
print(imzge[0][0][1])
print(imzp[1][0][0])

tensor(0.0418)
tensor(0.0418)


In [136]:
#indexing

In [137]:
import torch

In [138]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [139]:
x = torch.arange(1,10).reshape(3,3)
x , x.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [141]:
# Certainly! Let's break down the two tensors and their shapes, along with their visualizations.

# **First Tensor:**
# ```python
# (tensor([[[1, 2, 3],
#           [4, 5, 6],
#           [7, 8, 9]]]),
#  torch.Size([1, 3, 3]))
# ```

# **Second Tensor:**
# ```python
# (tensor([[1, 2, 3],
#          [4, 5, 6],
#          [7, 8, 9]]),
#  torch.Size([3, 3]))
# ```

# In both tensors, the actual data is the same: the numbers 1 to 9 arranged in a 3x3 grid. The difference lies in the structure of the tensors and their shapes.

# **Explanation and Visualization:**

# 1. **First Tensor:**
#    - The first tensor is a 3D tensor with a single "batch" dimension. This is indicated by the outer set of square brackets.
#    - Inside the batch, there is a 3x3 grid of numbers.
#    - The batch size is 1, and the tensor has dimensions `[1, 3, 3]`.

#    Visualization:
#    ```
#    Batch: 1
#    +---+---+---+
#    | 1 | 2 | 3 |
#    +---+---+---+
#    | 4 | 5 | 6 |
#    +---+---+---+
#    | 7 | 8 | 9 |
#    +---+---+---+
#    ```

# 2. **Second Tensor:**
#    - The second tensor is a 2D tensor without a batch dimension.
#    - It directly represents the 3x3 grid of numbers.
#    - The tensor has dimensions `[3, 3]`.

#    Visualization:
#    ```
#    +---+---+---+
#    | 1 | 2 | 3 |
#    +---+---+---+
#    | 4 | 5 | 6 |
#    +---+---+---+
#    | 7 | 8 | 9 |
#    +---+---+---+
#    ```

# In summary, the main difference is that the first tensor has an additional batch dimension, while the second tensor directly represents the 3x3 grid without the batch dimension. The choice of which tensor to use depends on the context and requirements of your data and computations.

In [142]:
# Certainly, let's create a tensor with a batch dimension of 2 and visualize it. Here's the code to create and visualize the tensor:

# ```python
# import torch

# # Create a tensor with batch dimension 2
# batched_tensor = torch.tensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
#                                [[10, 11, 12], [13, 14, 15], [16, 17, 18]]])

# # Print the tensor and its shape
# print("Batched tensor:")
# print(batched_tensor)
# print("\nTensor shape:", batched_tensor.shape)
# ```

# In this example, we've created a tensor with a batch dimension of 2. Each batch sample contains a 3x3 grid of numbers. Here's the visualization of the batched tensor:

# **Batch Sample 1:**
# ```
# +---+---+---+
# | 1 | 2 | 3 |
# +---+---+---+
# | 4 | 5 | 6 |
# +---+---+---+
# | 7 | 8 | 9 |
# +---+---+---+
# ```

# **Batch Sample 2:**
# ```
# +----+----+----+
# | 10 | 11 | 12 |
# +----+----+----+
# | 13 | 14 | 15 |
# +----+----+----+
# | 16 | 17 | 18 |
# +----+----+----+
# ```

# The batch dimension is represented by having two sets of batch samples. Each batch sample contains a 3x3 grid of numbers, and the two batch samples are processed together in parallel during computations.

# Remember that the order of the batch samples in the batch dimension is not significant; they are treated independently and processed concurrently.

In [144]:
x = torch.arange(1,10).reshape(1,3,3)
x , x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [145]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [146]:
x[1]

IndexError: ignored

In [147]:
x[0][0]

tensor([1, 2, 3])

In [148]:
x[0,0]

tensor([1, 2, 3])

In [149]:
x[0][0][0]

tensor(1)

In [150]:
x[0][0][3]

IndexError: ignored

In [151]:
x[1][1][1]

IndexError: ignored

In [153]:
x[0][2][2]

tensor(9)

In [154]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [155]:
x[:,0]

tensor([[1, 2, 3]])

In [157]:
x[:,:,0]

tensor([[1, 4, 7]])

In [158]:
x[:,:,1]

tensor([[2, 5, 8]])

In [160]:
x[:,1:3,1]

tensor([[5, 8]])

In [162]:
x[0,0,:]

tensor([1, 2, 3])

In [163]:
x[:,:,2]

tensor([[3, 6, 9]])

In [164]:
# numpy to torch torch.from_numpy(ndarray)
# torch to numpy torch.Tensor.numpy()

In [165]:
import torch
import numpy as np

In [167]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

In [168]:
array.dtype

dtype('float64')

In [171]:
torch.arange(1.0,3.0).dtype

torch.float32

In [173]:
array = np.arange(1.0,10.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [174]:
array = array + 1
array, tensor

(array([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [176]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [178]:
tensor = tensor + 1
tensor, numpy_tensor#they dont have shared memory

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))