<a href="https://colab.research.google.com/github/Carlos1729/todojson/blob/main/Pytorch_CS224n.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [28]:
import torch
import torch.nn as nn

In [29]:
list_of_lists = [
  [1, 2, 3],
  [4, 5, 6],
]
print(list_of_lists)

[[1, 2, 3], [4, 5, 6]]


In [30]:
# Initializing a tensor
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ])
print(data)

tensor([[0, 1],
        [2, 3],
        [4, 5]])


In [31]:
data = torch.tensor([
                     [0, 1],
                     [2, 3],
                     [4, 5]
                    ], dtype=torch.float32)
print(data)

tensor([[0., 1.],
        [2., 3.],
        [4., 5.]])


In [32]:
zeros = torch.zeros(3, 4)  # a tensor of all zeros
print(zeros)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [33]:
ones = torch.ones(3, 4)   # a tensor of all ones
print(ones)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


In [34]:
rr = torch.arange(1, 10) # range from [1, 10)
print(rr)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [35]:
rr + 2

tensor([ 3,  4,  5,  6,  7,  8,  9, 10, 11])

In [36]:
rr * 2

tensor([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [37]:
a = torch.tensor([[1, 2], [2, 3], [4, 5]])      # (3, 2)
b = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])  # (2, 4)  (3, 4)

print("A is", a)
print("B is", b)
print("The product is", a.matmul(b))
print("The other product is", a @ b) # +, -, *, @

A is tensor([[1, 2],
        [2, 3],
        [4, 5]])
B is tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
The product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])
The other product is tensor([[11, 14, 17, 20],
        [17, 22, 27, 32],
        [29, 38, 47, 56]])


In [38]:
v = torch.tensor([1, 2, 3])

In [39]:
v.shape

torch.Size([3])

In [40]:
torch.tensor([[1, 2, 3], [4, 5, 6]]) @ v  #(2, 3) @ (3)  -> (2)

tensor([14, 32])

In [41]:
matr_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(matr_2d.shape)
print(matr_2d)

torch.Size([2, 3])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [42]:
matr_3d = torch.tensor([[[1, 2, 3, 4], [-2, 5, 6, 9]], [[5, 6, 7, 2], [8, 9, 10, 4]], [[-3, 2, 2, 1], [4, 6, 5, 9]]])
print(matr_3d)
print(matr_3d.shape)

tensor([[[ 1,  2,  3,  4],
         [-2,  5,  6,  9]],

        [[ 5,  6,  7,  2],
         [ 8,  9, 10,  4]],

        [[-3,  2,  2,  1],
         [ 4,  6,  5,  9]]])
torch.Size([3, 2, 4])


In [43]:
rr = torch.arange(1, 16)
print("The shape is currently", rr.shape)
print("The contents are currently", rr)
print()
rr = rr.view(5, 3)
print("After reshaping, the shape is currently", rr.shape)
print("The contents are currently", rr)#view doesnt modify actual tensor

The shape is currently torch.Size([15])
The contents are currently tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

After reshaping, the shape is currently torch.Size([5, 3])
The contents are currently tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [44]:
import numpy as np

# numpy.ndarray --> torch.Tensor:
arr = np.array([[1, 0, 5]])
data = torch.tensor(arr)
print("This is a torch.tensor", data)

# torch.Tensor --> numpy.ndarray:
new_arr = data.numpy()
print("This is a np.ndarray", new_arr)

This is a torch.tensor tensor([[1, 0, 5]])
This is a np.ndarray [[1 0 5]]


In [45]:
data = torch.arange(1, 36, dtype=torch.float32).reshape(5, 7)
print("Data is:", data)

# We can perform operations like *sum* over each row...
print("Taking the sum over columns:")
print(data.sum(dim=0))

# or over each column.
print("Taking thep sum over rows:")
print(data.sum(dim=1))

# Other operations are available:
print("Taking the stdev over rows:")
print(data.std(dim=1))


Data is: tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11., 12., 13., 14.],
        [15., 16., 17., 18., 19., 20., 21.],
        [22., 23., 24., 25., 26., 27., 28.],
        [29., 30., 31., 32., 33., 34., 35.]])
Taking the sum over columns:
tensor([ 75.,  80.,  85.,  90.,  95., 100., 105.])
Taking thep sum over rows:
tensor([ 28.,  77., 126., 175., 224.])
Taking the stdev over rows:
tensor([2.1602, 2.1602, 2.1602, 2.1602, 2.1602])


In [46]:
data.sum()

tensor(630.)

In [47]:
# Initializing a tensor
data = torch.tensor([
                     [1, 2.2, 9.6],
                     [4, -7.2, 6.3]
                    ])
print(data)
print(data.shape)

tensor([[ 1.0000,  2.2000,  9.6000],
        [ 4.0000, -7.2000,  6.3000]])
torch.Size([2, 3])


In [48]:
data.mean(dim  = 0)#column

tensor([ 2.5000, -2.5000,  7.9500])

In [49]:
data.mean(dim  = 1)#row

tensor([4.2667, 1.0333])

In [50]:
# Initialize an example tensor
x = torch.Tensor([
                  [[1, 2], [3, 4]],
                  [[5, 6], [7, 8]],
                  [[9, 10], [11, 12]]
                 ])
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [51]:
x.shape

torch.Size([3, 2, 2])

In [53]:
x[0], x[1], x[2]

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[5., 6.],
         [7., 8.]]),
 tensor([[ 9., 10.],
         [11., 12.]]))

In [54]:
x[:,0]

tensor([[ 1.,  2.],
        [ 5.,  6.],
        [ 9., 10.]])

In [55]:
x[:,1]

tensor([[ 3.,  4.],
        [ 7.,  8.],
        [11., 12.]])

In [56]:
matr = torch.arange(1, 16).view(5, 3)
print(matr)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]])


In [57]:
matr[:,0]

tensor([ 1,  4,  7, 10, 13])

In [58]:
matr[0,:]

tensor([1, 2, 3])

In [60]:
matr[:2,:1]

tensor([[1],
        [4]])

In [63]:
matr.shape

torch.Size([5, 3])

In [66]:
matr[0][2],matr[4,2],matr[1,2]

(tensor(3), tensor(15), tensor(6))

In [69]:
matr[[0, 2, 4]]#print elements at those indices

tensor([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15]])

In [70]:
# Let's access the 0th elements of the 1st and 2nd elements
i = torch.tensor([1, 2])
j = torch.tensor([0])
matr[i, j]

tensor([4, 7])

In [72]:
matr[0, 0].item()

1

In [73]:
# Import pprint, module we use for making our print statements prettier
import pprint
pp = pprint.PrettyPrinter()

In [78]:
# Create an example tensor
# requires_grad parameter tells PyTorch to store gradients
x = torch.tensor([2.], requires_grad=True)

# Print the gradient if it is calculated
# Currently None since x is a scalar
pp.pprint(x.grad)

None


In [79]:
# Calculating the gradient of y with respect to x
y = x * x * 3 # 3x^2
y.backward()
pp.pprint(x.grad) # d(y)/d(x) = d(3x^2)/d(x) = 6x = 12

tensor([12.])


In [80]:
z = x * x * 3 # 3x^2
z.backward()
pp.pprint(x.grad)#this gets added each time because gradients have to be added accross several batches

tensor([24.])


In [81]:
import torch.nn as nn

In [83]:
input = torch.ones(2,3,4)
input

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [88]:
linear = nn.Linear(4, 2)#define the nn here

In [89]:
linear_output = linear(input)
linear_output

tensor([[[0.2345, 0.1430],
         [0.2345, 0.1430],
         [0.2345, 0.1430]],

        [[0.2345, 0.1430],
         [0.2345, 0.1430],
         [0.2345, 0.1430]]], grad_fn=<ViewBackward0>)

In [90]:
list(linear.parameters()) # Ax + b

[Parameter containing:
 tensor([[ 0.3366, -0.1465,  0.3122, -0.2671],
         [ 0.1880, -0.3126, -0.1133,  0.4820]], requires_grad=True),
 Parameter containing:
 tensor([-0.0006, -0.1012], requires_grad=True)]

In [91]:
tf = torch.tensor([[ 0.3366, -0.1465,  0.3122, -0.2671],
         [ 0.1880, -0.3126, -0.1133,  0.4820]])

In [93]:
tf.shape

torch.Size([2, 4])

In [94]:
2*3*4 * 4 * 2  #(W^T)

192

In [98]:
2*3*2 + 2 #correspoms to no of enties in first part of shape

14

In [95]:
b = torch.tensor([-0.0006, -0.1012])
b.shape

torch.Size([2])

In [97]:
linear_output.shape

torch.Size([2, 3, 2])

In [99]:
# Data of shape [batch_size, feature_dim] # 4
# [batch_size, output_dim] # 2

# linear layer of shape (feature_dim, output_dim)

In [100]:
sigmoid = nn.Sigmoid()
output = sigmoid(linear_output)
output

tensor([[[0.5584, 0.5357],
         [0.5584, 0.5357],
         [0.5584, 0.5357]],

        [[0.5584, 0.5357],
         [0.5584, 0.5357],
         [0.5584, 0.5357]]], grad_fn=<SigmoidBackward0>)

In [101]:
block = nn.Sequential(
    nn.Linear(4, 2),
    nn.Sigmoid()
)

input = torch.ones(2,3,4)
output = block(input)
output

tensor([[[0.2766, 0.4507],
         [0.2766, 0.4507],
         [0.2766, 0.4507]],

        [[0.2766, 0.4507],
         [0.2766, 0.4507],
         [0.2766, 0.4507]]], grad_fn=<SigmoidBackward0>)

In [102]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our model
    # There isn't anything specific about the naming of `self.model`. It could
    # be something arbitrary.
    self.model = nn.Sequential(
        nn.Linear(self.input_size, self.hidden_size),
        nn.ReLU(),
        nn.Linear(self.hidden_size, self.input_size),
        nn.Sigmoid()
    )

  def forward(self, x):
    output = self.model(x)
    return output

In [103]:
class MultilayerPerceptron(nn.Module):

  def __init__(self, input_size, hidden_size):
    # Call to the __init__ function of the super class
    super(MultilayerPerceptron, self).__init__()

    # Bookkeeping: Saving the initialization parameters
    self.input_size = input_size
    self.hidden_size = hidden_size

    # Defining of our layers
    self.linear = nn.Linear(self.input_size, self.hidden_size)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(self.hidden_size, self.input_size)
    self.sigmoid = nn.Sigmoid()

  def forward(self, x):
    linear = self.linear(x)
    relu = self.relu(linear)
    linear2 = self.linear2(relu)
    output = self.sigmoid(linear2)
    return output

In [104]:
# Make a sample input
input = torch.randn(2, 5)

# Create our model
model = MultilayerPerceptron(5, 3)

# Pass our input through our model
model(input)

tensor([[0.4882, 0.2525, 0.2984, 0.6468, 0.5510],
        [0.3834, 0.2355, 0.3322, 0.6266, 0.5479]], grad_fn=<SigmoidBackward0>)

In [105]:
list(model.named_parameters())

[('linear.weight',
  Parameter containing:
  tensor([[ 0.4149, -0.2710,  0.3242, -0.2710,  0.1462],
          [-0.2210, -0.2599,  0.3426, -0.0484,  0.4017],
          [ 0.1722, -0.3795,  0.2930,  0.3593, -0.2446]], requires_grad=True)),
 ('linear.bias',
  Parameter containing:
  tensor([-0.1384,  0.1108,  0.1530], requires_grad=True)),
 ('linear2.weight',
  Parameter containing:
  tensor([[-0.3925, -0.0220,  0.2021],
          [-0.2880, -0.1024, -0.3825],
          [-0.4484,  0.3371, -0.4057],
          [ 0.2353, -0.0883,  0.3530],
          [-0.4968,  0.4611,  0.0181]], requires_grad=True)),
 ('linear2.bias',
  Parameter containing:
  tensor([-0.2669, -0.4063, -0.1757,  0.0156,  0.2151], requires_grad=True))]

In [106]:
import torch.optim as optim

In [107]:
# Create the y data
y = torch.ones(10, 5)

# Add some noise to our goal y to generate our x
# We want out model to predict our original data, albeit the noise
x = y + torch.randn_like(y)
x

tensor([[ 1.2286,  1.8206,  1.4679,  2.1159, -0.3725],
        [ 1.2738,  0.0741,  2.3622, -1.2785,  0.2324],
        [ 0.1323,  3.1925,  2.4413,  1.7939,  0.4364],
        [ 0.8836,  0.5542,  1.5658,  2.1098,  1.1966],
        [ 1.1649,  1.3634,  2.4712,  0.9302,  0.6237],
        [ 0.2656,  3.5774, -0.5605,  0.3437, -1.8057],
        [-1.3451,  0.9541,  1.9330,  1.5842,  0.3641],
        [ 1.8276,  0.1832,  2.6942,  0.9522,  2.9299],
        [ 1.0903,  1.6154,  1.0383,  0.8268,  1.8320],
        [ 0.6308,  0.5309,  0.3637, -0.3623, -1.6990]])

In [108]:
# Instantiate the model
model = MultilayerPerceptron(5, 3)

# Define the optimizer
adam = optim.Adam(model.parameters(), lr=1e-1)

# Define loss using a predefined loss function
loss_function = nn.BCELoss()

# Calculate how our model is doing now
y_pred = model(x)
loss_function(y_pred, y).item()

0.65936279296875

In [109]:
# Set the number of epoch, which determines the number of training iterations
n_epoch = 10

for epoch in range(n_epoch):
  # Set the gradients to 0
  adam.zero_grad()

  # Get the model predictions
  y_pred = model(x)

  # Get the loss
  loss = loss_function(y_pred, y)

  # Print stats
  print(f"Epoch {epoch}: traing loss: {loss}")

  # Compute the gradients
  loss.backward()

  # Take a step to optimize the weights
  adam.step()


Epoch 0: traing loss: 0.65936279296875
Epoch 1: traing loss: 0.42856085300445557
Epoch 2: traing loss: 0.24497827887535095
Epoch 3: traing loss: 0.1294879913330078
Epoch 4: traing loss: 0.06940020620822906
Epoch 5: traing loss: 0.03960249945521355
Epoch 6: traing loss: 0.024077698588371277
Epoch 7: traing loss: 0.01482950709760189
Epoch 8: traing loss: 0.008848834782838821
Epoch 9: traing loss: 0.0052063800394535065


In [110]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.6462, -0.7399, -0.2536, -0.6277, -0.2511],
         [ 0.9576,  0.6966,  0.7211,  0.7966,  0.0648],
         [ 0.7727,  1.1602,  0.9451,  0.8630,  0.6283]], requires_grad=True),
 Parameter containing:
 tensor([-0.4347,  1.2415,  0.4680], requires_grad=True),
 Parameter containing:
 tensor([[ 7.0035e-01,  1.2324e+00,  9.8657e-01],
         [ 1.7090e-01,  1.2274e+00,  6.4281e-01],
         [ 8.4333e-01,  1.3285e+00,  1.2087e+00],
         [-2.3187e-04,  1.0686e+00,  8.5789e-01],
         [ 1.3781e-01,  1.3577e+00,  7.9528e-01]], requires_grad=True),
 Parameter containing:
 tensor([1.1836, 0.3966, 0.9239, 0.2070, 0.4367], requires_grad=True)]