<a href="https://colab.research.google.com/github/Carlos1729/todojson/blob/main/Pytorch_Fundamentals_Madhukar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
#Random Tensors
import torch

In [6]:
random_tensor = torch.rand(3,4)
print(random_tensor)#ndims will be what goes inside .rand

tensor([[0.0039, 0.9949, 0.2167, 0.0545],
        [0.1743, 0.9227, 0.2645, 0.4770],
        [0.5637, 0.9923, 0.9547, 0.2404]])


In [7]:
random_tensor.ndim

2

In [8]:
random_image_tensor = torch.rand(224,224,3) #similar to an rcb image tensor

In [10]:
random_image_tensor, random_image_tensor.shape, random_image_tensor.ndim

(tensor([[[0.3194, 0.3217, 0.4727],
          [0.7609, 0.6142, 0.2662],
          [0.6173, 0.2908, 0.1293],
          ...,
          [0.9740, 0.7518, 0.2941],
          [0.0799, 0.4008, 0.2376],
          [0.2160, 0.5581, 0.4108]],
 
         [[0.7198, 0.6244, 0.2439],
          [0.6602, 0.2214, 0.3040],
          [0.3196, 0.8695, 0.9031],
          ...,
          [0.1698, 0.9686, 0.8116],
          [0.8310, 0.6039, 0.4049],
          [0.6611, 0.2368, 0.0251]],
 
         [[0.7322, 0.9422, 0.9151],
          [0.6742, 0.3470, 0.4765],
          [0.5422, 0.5223, 0.7284],
          ...,
          [0.7117, 0.7261, 0.1034],
          [0.5223, 0.7210, 0.2815],
          [0.0544, 0.1036, 0.0578]],
 
         ...,
 
         [[0.5802, 0.5888, 0.5825],
          [0.0805, 0.3195, 0.7367],
          [0.9400, 0.4749, 0.6118],
          ...,
          [0.1781, 0.8267, 0.9207],
          [0.5634, 0.8463, 0.1429],
          [0.5208, 0.0223, 0.4146]],
 
         [[0.7181, 0.8056, 0.0890],
          [0

In [11]:
#zeroes and ones tensors

In [14]:
zeros = torch.zeros(3,4)

In [15]:
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [36]:
ones = torch.ones(4,3)

In [38]:
ones , ones.dtype

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]),
 torch.float32)

In [19]:
torch.range(0,10)

<ipython-input-19-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [20]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
r = torch.arange(1,10,2)
r

tensor([1, 3, 5, 7, 9])

In [29]:
#create a tensor with similar shape of another given tensor
zeros = torch.zeros_like(r)
zeros
ones = torch.ones_like(r)
ones  #the _like doest work with torch.rand why

tensor([1, 1, 1, 1, 1])

In [39]:
tenso = torch.rand(3,4,dtype=torch.float16)
tenso

tensor([[0.1958, 0.2412, 0.2422, 0.7686],
        [0.2124, 0.1938, 0.4414, 0.4058],
        [0.4438, 0.1753, 0.4785, 0.1699]], dtype=torch.float16)

In [34]:
# dtype - type of elements inside the tensor
# device - if gpu enabled cuda, or else cpu
# requires - grad wether or not to track gradients with these operations

In [44]:
ones.shape, tenso.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [46]:
# ones * tenso * is for element wise multiplication for matrix multiplication use @
ones @ tenso

RuntimeError: ignored

In [47]:
tenso = torch.rand(3,4,dtype=torch.float32)
tenso

tensor([[0.6027, 0.2679, 0.5171, 0.6216],
        [0.4614, 0.6848, 0.2681, 0.1678],
        [0.1035, 0.8133, 0.2678, 0.3228]])

In [48]:
ones @ tenso

tensor([[1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122]])

In [49]:
print(tenso.dtype)
print(tenso.shape)
print(tenso.device)

torch.float32
torch.Size([3, 4])
cpu


In [50]:
##Manipulating tensors

In [54]:
zeros = torch.zeros(3,4)

In [55]:
ones + tenso

RuntimeError: ignored

In [56]:
zeros.shape , tenso.shape

(torch.Size([3, 4]), torch.Size([3, 4]))

In [57]:
zeros + tenso

tensor([[0.6027, 0.2679, 0.5171, 0.6216],
        [0.4614, 0.6848, 0.2681, 0.1678],
        [0.1035, 0.8133, 0.2678, 0.3228]])

In [58]:
zeros - tenso

tensor([[-0.6027, -0.2679, -0.5171, -0.6216],
        [-0.4614, -0.6848, -0.2681, -0.1678],
        [-0.1035, -0.8133, -0.2678, -0.3228]])

In [60]:
ones - tenso

RuntimeError: ignored

In [61]:
zeros * tenso

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [62]:
ones * tenso

RuntimeError: ignored

In [63]:
ones @ tenso

tensor([[1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122]])

In [65]:
zeros @ tenso

RuntimeError: ignored

In [68]:
torch.matmul(ones,tenso)

tensor([[1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122]])

In [67]:
torch.matmul(zeros,tenso)

RuntimeError: ignored

In [69]:
torch.mm(ones,tenso)

tensor([[1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122],
        [1.1677, 1.7659, 1.0530, 1.1122]])

In [70]:
zeros @ tenso.T #take the teranspose

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [72]:
tenso.min()

tensor(0.1035)

In [73]:
tenso.max()

tensor(0.8133)

In [75]:
tenso.mean() #this worked because the dtypre is not int

tensor(0.4249)

In [76]:
tenso.sum()

tensor(5.0988)

In [78]:
tenso.argmin()#1d based indexing

tensor(8)

In [79]:
tenso.argmax()

tensor(9)